services:
  auth-service:
    container_name: auth-service
    build: 
      context: ..
      dockerfile: Dockerfile
    command: "uvicorn --factory application.api.v1.main:create_app --host=0.0.0.0 --reload --port 8000"
    volumes:
      - ../app:/app/
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    restart: always