services:
  db:
    image: postgres:17.2
    container_name: db-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"  # Использование порта 5433 снаружи, 5432 внутри контейнера
    volumes:
      - .postgres:/var/lib/postgresql/data
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - backend

volumes:
  db:
    driver: local

networks:
  backend:
    driver: bridge
